### ISSUE TITLE
notion-enhancer module

### ISSUE THREAD

**Issue by dragonwocky** [alexander-kazakov/notion-layout-extension#1]
Hey!

I work on the [notion-enhancer](https://github.com/dragonwocky/notion-enhancer), a script that mods the desktop app to add custom theming and scripting (e.g. a hotkey to toggle window visibility). I'm working on transitioning it from a simple mod to a proper mod-loader, and I was hoping to be able to include this as a mod (you'd be properly attributed for it, of course).

If that's alright with you, please let me know as soon as possible so I can make this something as many notion users can benefit from as possible :)

**Comment by alexander-kazakov** [comment]
@dragonwocky  For sure, please feel free to reuse any of this code in your work!

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/
notion-enhancer v0.8 now released.
